name: hairstylesapp
description: A new Flutter project for Hair Styles App.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  # Flavor
  flutter_flavor: ^3.1.0
  # Device Preview
  device_preview: ^1.1.0
  # Local Caching
  shared_preferences: ^2.0.15
  # Http Interceptor
  dio: ^4.0.0
  # Connectivity Helper
  connectivity: ^3.0.3
  # Http Logger
  pretty_dio_logger: ^1.1.1
  # flutter_svg: ^0.22.0
  flutter_svg: ^1.1.3
  # Dialogs
  material_dialogs: ^1.1.1
  # Loading Dialog
  flutter_easyloading: ^3.0.3
  #For responsiveness
  flutter_screenutil: ^5.0.0+2
  #for sms autofill
#  sms_autofill: ^2.2.0
  #for pick image
  image_picker: ^0.8.4+3
  # Pull to Refresh
  pull_to_refresh: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
